### ISSUE TITLE
「Powered by : SAKURA Internet」を追加

### ISSUE THREAD

**Issue by UEDEU** [FlexiblePrintedCircuits/covid19-mie#106]
- 北海道版対策サイトのようにする
![image](https://user-images.githubusercontent.com/47916753/77434662-8ce64280-6e24-11ea-9ac1-332bb0bd03c8.png)
https://stopcovid19.hokkaido.dev/

**Comment by sakurum** [comment]
案外重かったのでちょっと時間かかります🙏
