### ISSUE TITLE
README等のリンク先をさくらに修正

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#112]
## 改善詳細 / Details of Improvement
- 旧来のリンクhttps://covid19-mie.netlify.com/ を全て 新規のリンクhttps://mie.stopcovid19.jp に修正

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shoma3571** [comment]
やります
