### ISSUE TITLE
「他の自治体の対策サイト」の表記を追加

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#113]
## 改善詳細 / Details of Improvement
- サイドバーに追加する　

## スクリーンショット / Screenshot

<img width="419" alt="スクリーンショット 2020-03-27 13 22 53" src="https://user-images.githubusercontent.com/34621864/77721439-3ea48f80-702e-11ea-8051-5152d7221270.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shoma3571** [comment]
やります
