### ISSUE TITLE
三重県のLINEへのリンクを追加

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#143]
## 改善詳細 / Details of Improvement
三重県の新型コロナ対策のLINEがあるので、それへのリンクを追加する
https://www.pref.mie.lg.jp/YAKUMUS/HP/m0068000078.htm

## スクリーンショット / Screenshot
<img width="1439" alt="スクリーンショット 2020-04-10 15 42 05" src="https://user-images.githubusercontent.com/34621864/78969445-e9926e80-7b41-11ea-88ee-f084dc7edc85.png">

## 期待する見せ方・挙動 / Expected behavior
サイドナビゲーションバーに追加
<img width="575" alt="スクリーンショット 2020-04-10 15 43 52" src="https://user-images.githubusercontent.com/34621864/78969523-16df1c80-7b42-11ea-9a9b-a296773f899e.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shoma3571** [comment]
やります
