### ISSUE TITLE
知事からのメッセージを三重県知事のものに差し替え

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#16]
## 起こっている問題 / The Problem
- リンク先が都知事のものになっている

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sakurum** [comment]
新型コロナウイルスについて知事からのメッセージが存在するので差し替えます

**Comment by FlexiblePrintedCircuits** [comment]
これもうしょうま君が対応済ですよ

**Comment by FlexiblePrintedCircuits** [comment]
最新のdevelopブランチを見てみてください

**Comment by sakurum** [comment]
申し訳ない対応してた

**Comment by sakurum** [comment]
#3 これでした
