### ISSUE TITLE
「陽性患者の属性」のグラフの表記の改善提案

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#56]
## 改善詳細 / Details of Improvement
「3/12の累計」は、3/12の一日だけの累計なのか3/12までの累計なのか、両方の意味に取れるので、「3/12までの累計」の方が誤解がない

## スクリーンショット / Screenshot

<img width="870" alt="スクリーンショット 2020-03-13 17 13 52" src="https://user-images.githubusercontent.com/34621864/76602341-1016b700-654e-11ea-9d08-191aab3afabc.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by FlexiblePrintedCircuits** [comment]
やります
