### ISSUE TITLE
現状で公開されている情報のみグラフにする

### ISSUE THREAD

**Issue by sakurum** [FlexiblePrintedCircuits/covid19-mie#7]
## 起こっている問題 / The Problem
- 東京都版にあるすべてのグラフを作成することはデータがないためできない。
- 現状で公開されているデータのみで作成できるグラフを検討する。
- 使用しないものについてはコメントアウトで対応する（※検討が必要?）

**Comment by UEDEU** [comment]
やります

**Comment by UEDEU** [comment]
やります

**Comment by sakurum** [comment]
> やります
ちょっと課題がおもすぎるので細分化して進めませんか..?
1. スクレイピング元の決定
2. 最終的に扱うデータ形式の確認
3. スクレイピング、変換の検討
4. 実装
くらいに分けてすすめたい

**Comment by UEDEU** [comment]
@sakurum 了解です
